=== ivos/clojure-rest-jdbc-backend/test/it/dataset.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:la="http://lightair.sourceforge.net/">
	<xsd:import namespace="http://lightair.sourceforge.net/" schemaLocation="light-air-types.xsd"/>

	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="project" type="project__Type"/>
				<xsd:element name="session" type="session__Type"/>
				<xsd:element name="user" type="user__Type"/>
				<xsd:element name="schema_version" type="schema_version__Type"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="project__Type">
		<xsd:attribute name="id" use="optional" type="la:LongType"/>
		<xsd:attribute name="version" use="optional" type="la:LongType"/>
		<xsd:attribute name="code" use="optional" type="la:StringType"/>
		<xsd:attribute name="name" use="optional" type="la:StringType"/>
		<xsd:attribute name="visibility" use="optional" type="la:StringType"/>
		<xsd:attribute name="description" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="start" use="optional" type="la:DateNullableType"/>
		<xsd:attribute name="duration" use="optional" type="la:IntegerNullableType"/>
		<xsd:attribute name="budget" use="optional" type="la:BigdecimalNullableType"/>
		<xsd:attribute name="daily_meeting_at" use="optional" type="la:TimeNullableType"/>
		<xsd:attribute name="kick_off" use="optional" type="la:TimestampNullableType"/>
		<xsd:attribute name="created" use="optional" type="la:TimestampType"/>
	</xsd:complexType>
	<xsd:complexType name="session__Type">
		<xsd:attribute name="token" use="optional" type="la:StringType"/>
		<xsd:attribute name="created" use="optional" type="la:TimestampType"/>
		<xsd:attribute name="duration" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="expires" use="optional" type="la:TimestampType"/>
		<xsd:attribute name="user" use="optional" type="la:LongType"/>
	</xsd:complexType>
	<xsd:complexType name="user__Type">
		<xsd:attribute name="id" use="optional" type="la:LongType"/>
		<xsd:attribute name="version" use="optional" type="la:LongType"/>
		<xsd:attribute name="username" use="optional" type="la:StringType"/>
		<xsd:attribute name="email" use="optional" type="la:StringType"/>
		<xsd:attribute name="name" use="optional" type="la:StringType"/>
		<xsd:attribute name="password_hash" use="optional" type="la:StringType"/>
		<xsd:attribute name="status" use="optional" type="la:StringType"/>
		<xsd:attribute name="roles" use="optional" type="la:StringType"/>
	</xsd:complexType>
	<xsd:complexType name="schema_version__Type">
		<xsd:attribute name="installed_rank" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="version" use="optional" type="la:StringNullableType"/>
		<xsd:attribute name="description" use="optional" type="la:StringType"/>
		<xsd:attribute name="type" use="optional" type="la:StringType"/>
		<xsd:attribute name="script" use="optional" type="la:StringType"/>
		<xsd:attribute name="checksum" use="optional" type="la:IntegerNullableType"/>
		<xsd:attribute name="installed_by" use="optional" type="la:StringType"/>
		<xsd:attribute name="installed_on" use="optional" type="la:TimestampType"/>
		<xsd:attribute name="execution_time" use="optional" type="la:IntegerType"/>
		<xsd:attribute name="success" use="optional" type="la:BooleanType"/>
	</xsd:complexType>
</xsd:schema>

=== ivos/clojure-rest-jdbc-backend/test/it/session/list/setup.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../dataset.xsd">

	<user id="1534984901" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="active" roles="user"/>
	<user id="1534984902" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="disabled" roles="user"/>
	<user id="1534984903" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="active" roles="user"/>
	<!--current-->
	<user id="1534984904" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="active" roles="user,admin"/>

	<!--included:-->
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp+PT1M" user="1534984901"/>
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp+PT2M" user="1534984902"/>
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp+PT3M" user="1534984903"/>
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp+P3M" user="1534984903"/>

	<!--expired-->
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp-PT1M" user="1534984903"/>
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp-P3M" user="1534984903"/>

	<!--included-->
	<session token="@auto" created="@auto" duration="@auto" expires="@timestamp+PT1M" user="1534984901"/>

	<!--explicit temporal values-->
	<session token="@auto" created="2016-09-10T12:34:56.987Z" duration="@auto" expires="2301-09-11T12:35:56.987Z"
	         user="1534984901"/>

	<!--current-->
	<session token="7b0e6756-d9e4-4001-9d53-000000000001" created="@auto" duration="90" expires="@timestamp+PT1M"
	         user="1534984904"/>

	<!--included in order: 8 4 9 3 2 7 1-->
</dataset>

=== ivos/clojure-rest-jdbc-backend/test/it/generic/authorized-setup.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../dataset.xsd">

	<!--other roles-->
	<user id="1534984901" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="active" roles="user,other1,other2"/>
	<session token="other" created="@auto" duration="90" expires="@timestamp+PT1M" user="1534984901"/>

	<!--single correct role-->
	<user id="1534984902" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="active" roles="admin"/>
	<session token="single" created="@auto" duration="90" expires="@timestamp+PT1M" user="1534984902"/>

	<!--multiple roles, authorized-->
	<user id="1534984903" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="active" roles="user,admin,other1"/>
	<session token="multiple" created="@auto" duration="90" expires="@timestamp+PT1M" user="1534984903"/>

	<!--disabled-->
	<user id="1534984904" version="@auto" username="@auto" email="@auto" name="@auto" password_hash="@auto"
	      status="disabled" roles="admin"/>
	<session token="disabled" created="@auto" duration="90" expires="@timestamp+PT1M" user="1534984904"/>

</dataset>
